// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_auth_facebook': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"6bj10hwkok","name":"todosCRUD","description":"","endpoint":"https://6bj10hwkok.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/todos","/todos/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:70bbe7d1-b9d1-4bc4-b739-2620cf78b360',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'helloworld-hosting-mobilehub-201019885',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3ofk6vc9iseye.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"helloworld-mobilehub-201019885-todos","attributes":[{"name":"userId","type":"S"},{"name":"id","type":"S"},{"name":"date","type":"S"},{"name":"done","type":"BOOL"},{"name":"name","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"userId","rangeKey":"id"}],
    'aws_facebook_app_id': '274108833121643',
    'aws_facebook_app_permissions': 'public_profile',
    'aws_mobile_analytics_app_id': '5ecf5a275ea04d71bb653bafcd5c1975',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '5241299f-bc01-43c3-bd99-cb257ea241fb',
    'aws_project_name': 'HelloWorld',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'helloworld-deployments-mobilehub-201019885',
    'aws_resource_name_prefix': 'helloworld-mobilehub-201019885',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_p15CPu08Q',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '6j4srl345sqlpilv8jcu6hpmqh',
}

export default awsmobile;
